name: LuigiPipelineManual

on:
  workflow_dispatch:
    inputs:
      statesDistricts:
        description: 'states and districts json configuration'
        required: true
        default: '{ "MH": ["Mumbai", "Pune", "Nanded", "Raigad"], "UP": ["Agra"]  }'
      startDate:
        description: 'start date for metrics'
        required: true
        default: '2020-04-20'
      elderlyPage:
        description: 'page for the elderly table scrapping'
        required: true
        default: 0
      dailyCaseGrowthPage:
        description: 'page for the daily case growth table'
        required: true
        default: 23
      positiveBreakdownIndex:
        description: 'page for the positive breakdown table'
        required: true
        default: 20

jobs:
  pipelineManual:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # necessary for tabula-py
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      working-directory: ./pipeline
      run: |
        pip install -r requirements.txt
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: luigi pipeline
      env:
        SWB_DROPBOX_TOKEN: ${{ secrets.SWB_DROPBOX_TOKEN }}
      working-directory: ./pipeline
      run: |
        python -m luigi --module pipeline.tasks SWBPipelineWrapper --elderly-page ${{ github.event.inputs.elderlyPage }} --daily-case-growth-page ${{ github.event.inputs.dailyCaseGrowthPage }} --positive-breakdown-index ${{ github.event.inputs.positiveBreakdownIndex }}  --states-and-districts '${{ github.event.inputs.statesDistricts }}' --start-date ${{ github.event.inputs.startDate }} --local-scheduler
